config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pilots
  resources :planes
  resources :appointments
  root to: "appointments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :pilot
    belongs_to :plane
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :appointments
    has_many :planes, through: :appointments

    validates :name, presence: true, uniqueness: true
    validates :age, presence: true, numericality: { only_integer: true }
    validates :pic, presence: true, uniqueness: true
end

app/models/plane.rb
class Plane < ApplicationRecord
    has_many :appointments
    has_many :pilots, through: :appointments

    validates :model, presence: true
    validates :registration, presence: true, uniqueness: true
    validates :manufacturer, presence: true
    validates :range, presence: true, numericality: { only_integer: true }
    validates :age, presence: true, numericality: { only_integer: true }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:plane_id,:pilot_id)
    end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: [:show, :edit, :update, :destroy]

  # GET /pilots
  # GET /pilots.json
  def index
    @pilots = Pilot.all
  end

  # GET /pilots/1
  # GET /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots
  # POST /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: 'Pilot was successfully created.' }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1
  # PATCH/PUT /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: 'Pilot was successfully updated.' }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url, notice: 'Pilot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pilot_params
      params.require(:pilot).permit(:name,:age,:pic)
    end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:model,:manufacturer,:range,:age,:registration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pilot_helper.rb
module PilotHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <%= form.label :plane_id %><br>
    <%= form.collection_select(:plane_id, Plane.all, :id, :model, {:class => 'form-control'}) %>
  </div>
  <br>
  <div class="form">
    <%= form.label :pilot_id %><br>
    <%= form.collection_select(:pilot_id, Pilot.all, :id, :name, {:class => 'form-control'}) %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Appointments</h1>
<p id="notice"><%= notice %></p>
<%= link_to 'New Appointment', new_appointment_path %>
<br>
<br>
<% if Appointment.first.nil? %>
  <h2 class="text-primary">No Appointments Yet :(</h2>
<% end %>
<br>
<table class="table">
  <thead class="thead-dark">
    <% @appointments.each do |appointment| %>  
      <tr>
        <td><%= appointment.created_at %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%#= link_to 'Pilots', pilots_path %>
<%#= link_to 'Planes', planes_path%>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
<%= link_to 'Back', appointments_path %>
<br>
<br>
<%= render 'form', appointment: @appointment %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>
<br>
<br>
<p><%= Pilot.find(@appointment.pilot_id).name %> is booked to rent <%= Plane.find(@appointment.plane_id).registration %></p>
<p class="bg-light">Appointment was created at <%= @appointment.created_at %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/appointments">Appointments <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/planes">Planes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pilots">Pilots</a>
          </li>
        </ul>
      </div>
    </nav>
    <br>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pilots/_form.html.erb
<%= form_with(model: pilot, local: true) do |form| %>
  <% if pilot.errors.any? %>
    <% pilot.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :name %>:<br>
    <%= form.text_field :name, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="field">
    <%= form.label :age %>:<br>
    <%= form.text_field :age, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="field">
    <%= form.label :pic %>:<br>
    <%= form.text_field :pic, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/pilots/edit.html.erb
<h1>Editing Pilot</h1>
<br>
<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %>
<br>
<br>
<%= render 'form', pilot: @pilot %>

app/views/pilots/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Pilots</h1>
<br>
<%= link_to 'New Pilot', new_pilot_path %>
<br>
<br>
<table class="table">
  <thead class="thead-dark">
    <% @pilots.each_with_index do |pilot, index| %>
      <% if index % 2 == 0 %>
        <tr>
      <% else %>
        <tr class="bg-light">
      <% end %>
        <td><%= pilot.name %></td>
        <td><%= link_to 'Show', pilot %></td>
        <td><%= link_to 'Edit', edit_pilot_path(pilot) %></td>
        
        <% if pilot.appointments.length != 0 %>
          <td>In Use</td>
        <% else %>
          <td><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%#= link_to 'Appointments', appointments_path %>

app/views/pilots/new.html.erb
<h1>New Pilot</h1>
<br>
<%= link_to 'Back', pilots_path %>
<br>
<br>
<%= render 'form', pilot: @pilot %>

app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>
<br>
<br>
<img src="<%= @pilot.pic %>" width="250px" alt="pic"><br>
<h2>Name: <%= @pilot.name%></h2>
<h2 class="bg-light">Age: <%= @pilot.age%></h2>

app/views/planes/_form.html.erb
<%= form_with(model: plane, local: true) do |form| %>
  <% if plane.errors.any? %>
    <% plane.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>
  <div class="field">
    <%= form.label :model %><br>
    <%= form.text_field :model, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="field">
    <%= form.label :registration %><br>
    <%= form.text_field :registration, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="field">
    <%= form.label :manufacturer %><br>
    <%= form.text_field :manufacturer, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="field">
    <%= form.label :age %><br>
    <%= form.text_field :age, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="field">
    <%= form.label :range %><br>
    <%= form.text_field :range, {:class => 'form-control'} %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>
<br>
<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>
<br>
<br>
<%= render 'form', plane: @plane %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Planes</h1>
<br>
<%= link_to 'New Plane', new_plane_path %>
<br>
<br>
<table class="table">
  <thead class="thead-dark">
    <% @planes.each_with_index do |plane, index| %>
      <% if index % 2 == 0 %>
        <tr>
      <% else %>
        <tr class="bg-light">
      <% end %>
        <td><%= plane.model %></td>
        <td><%= plane.registration %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        
        <% if plane.appointments.length != 0 %>
          <td>In Use</td>
        <% else %>
          <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%#= link_to 'Appointments', appointments_path %>

app/views/planes/new.html.erb
<h1>New Plane</h1>
<br>
<%= link_to 'Back', planes_path %>
<br>
<br>
<%= render 'form', plane: @plane %>
  

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-sm-12">
            <p>Model: <%= @plane.model%></p>
            <p class="bg-light">Registration: <%= @plane.registration%></p>
            <p>Manufacturer: <%= @plane.manufacturer%></p>
            <p class="bg-light">Age: <%= @plane.age%></p>
            <p>Range: <%= @plane.range%></p><br>
        </div>
        <div class="col-md-6 col-sm-12">
            <div id='map'></div>
        </div>
    </div>
</div>

<script>
    radius = parseInt('<%= @plane.range %>')
    function initMap() {
        var myLatLng = {lat: 51.331231, lng: 0.032755};

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: myLatLng,
            disableDefaultUI: true
        });

        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Airport'  
        });

        var range = new google.maps.Circle({
            strokeColor: '#A9A9A9',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#000000',
            fillOpacity: 0.35,
            map: map,
            center: myLatLng,
            radius: radius * 1000
        });

        range.bindTo('center', marker, 'position');
        map.fitBounds(range.getBounds());
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAceHPKoSuyrSA3yjGsb-krlu7O1oG7Moo&callback=initMap"></script>